export interface TaskTemplate {
  title: string;
  description: string;
  category:
    | "kitchen"
    | "bathroom"
    | "living"
    | "bedroom"
    | "laundry"
    | "outdoor"
    | "pets"
    | "general";
  zone: string;
  estimated_minutes: number;
  is_emergency: boolean;
  recurrence_type:
    | "daily"
    | "weekly"
    | "biweekly"
    | "monthly"
    | "quarterly"
    | "yearly";
  tips: string[];
  sort_order: number;
}

export const TASK_TEMPLATES_SEED: TaskTemplate[] = [
  // ===== DAILY (יומי) - sort_order 1-20 =====
  {
    title: "שטיפת כלים / הפעלת מדיח",
    description: "שטיפת כלים ביד או הפעלת מדיח כלים לאחר ארוחות",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 15,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "שטפו כלים מיד אחרי האוכל - קל יותר לנקות",
      "הפעילו מדיח כשהוא מלא לחסוך מים וחשמל",
    ],
    sort_order: 1,
  },
  {
    title: "ניקוי משטחי עבודה במטבח",
    description: "ניגוב וחיטוי משטחי העבודה במטבח לאחר כל שימוש",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 5,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "השתמשו בחומר חיטוי מתאים למשטח",
      "נגבו שיירי מזון מיד למניעת חרקים",
    ],
    sort_order: 2,
  },
  {
    title: "טאטוא רצפת מטבח",
    description: "טאטוא מהיר של רצפת המטבח להסרת פירורים ולכלוך",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 5,
    is_emergency: false,
    recurrence_type: "daily",
    tips: [
      "טאטאו מהפינות לכיוון המרכז",
      "שימו לב מתחת לשולחן ולארונות",
    ],
    sort_order: 3,
  },
  {
    title: "הוצאת אשפה",
    description: "הוצאת שקית אשפה מלאה והחלפתה בחדשה",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 5,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "אל תחכו שהשקית תהיה מלאה מדי - קשה להוציא",
      "הפרידו פסולת אורגנית למיחזור",
    ],
    sort_order: 4,
  },
  {
    title: "סידור שיש המטבח",
    description: "החזרת חפצים למקומם וסידור שיש המטבח",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 3,
    is_emergency: false,
    recurrence_type: "daily",
    tips: [
      "החזירו כל דבר למקומו הקבוע",
      "שיש נקי = מטבח שנראה מסודר",
    ],
    sort_order: 5,
  },
  {
    title: "האכלת חתולים (בוקר)",
    description: "הגשת ארוחת בוקר לחתולים - מזון יבש ו/או רטוב",
    category: "pets",
    zone: "בעלי חיים",
    estimated_minutes: 5,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "הקפידו על שעות קבועות לארוחות",
      "בדקו שהקערה נקייה לפני מילוי",
    ],
    sort_order: 6,
  },
  {
    title: "האכלת חתולים (ערב)",
    description: "הגשת ארוחת ערב לחתולים - מזון יבש ו/או רטוב",
    category: "pets",
    zone: "בעלי חיים",
    estimated_minutes: 5,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "שמרו על כמות מזון קבועה למניעת השמנה",
      "מזון רטוב לא צריך להישאר בחוץ יותר מ-30 דקות",
    ],
    sort_order: 7,
  },
  {
    title: "מים טריים לחתולים",
    description: "החלפת מים בקערת השתייה של החתולים",
    category: "pets",
    zone: "בעלי חיים",
    estimated_minutes: 2,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "החליפו מים לפחות פעם ביום",
      "חתולים מעדיפים מים זורמים - שקלו מזרקת מים",
    ],
    sort_order: 8,
  },
  {
    title: "ניקוי ארגז חול",
    description: "ניקוי יומי של ארגז החול - הסרת גושים ופסולת",
    category: "pets",
    zone: "בעלי חיים",
    estimated_minutes: 5,
    is_emergency: true,
    recurrence_type: "daily",
    tips: [
      "נקו לפחות פעם ביום",
      "החליפו חול לגמרי פעם בשבוע",
    ],
    sort_order: 9,
  },
  {
    title: "איסוף בגדים מלוכלכים לסל",
    description: "איסוף בגדים מפוזרים והכנסתם לסל הכביסה",
    category: "general",
    zone: "כללי",
    estimated_minutes: 3,
    is_emergency: false,
    recurrence_type: "daily",
    tips: [
      "שימו סל כביסה בכל חדר שינה",
      "הפרידו צבעים מלבנים כבר בשלב האיסוף",
    ],
    sort_order: 10,
  },
  {
    title: "סידור מהיר של הסלון",
    description: "החזרת כריות למקום, סידור שולחן וניקוי שטחי",
    category: "living",
    zone: "סלון",
    estimated_minutes: 5,
    is_emergency: false,
    recurrence_type: "daily",
    tips: [
      "הקדישו 5 דקות לפני השינה לסידור",
      "כל דבר צריך מקום קבוע - ככה קל לסדר",
    ],
    sort_order: 11,
  },
  {
    title: "איוורור הבית (פתיחת חלונות)",
    description: "פתיחת חלונות לאיוורור ורענון האוויר בבית",
    category: "general",
    zone: "כללי",
    estimated_minutes: 2,
    is_emergency: false,
    recurrence_type: "daily",
    tips: [
      "פתחו חלונות בבוקר ל-15 דקות לפחות",
      "איוורור צולב (חלונות מנגד) יעיל יותר",
    ],
    sort_order: 12,
  },

  // ===== WEEKLY (שבועי) - sort_order 21-50 =====
  {
    title: "ניקוי עמוק של כיריים",
    description: "ניקוי יסודי של הכיריים כולל מבערים ומשטח",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו בסודה לשתייה לכתמים קשים",
      "הסירו מבערים ושרו במים חמים עם סבון",
    ],
    sort_order: 21,
  },
  {
    title: "ניקוי חיצוני של מקרר",
    description: "ניגוב דלתות המקרר, ידיות וחזית",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו במטלית מיקרופייבר לחה",
      "נגבו גם את הידיות שנוגעים בהן הרבה",
    ],
    sort_order: 22,
  },
  {
    title: "ניקוי מיקרוגל",
    description: "ניקוי פנימי וחיצוני של המיקרוגל",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "חממו קערת מים עם לימון ל-3 דקות - הקיטור מרכך לכלוך",
      "נגבו מיד אחרי כל שימוש למניעת הצטברות",
    ],
    sort_order: 23,
  },
  {
    title: "ארגון מזווה",
    description: "בדיקת תאריכי תפוגה, ארגון מדפים וסידור מוצרים",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "שימו מוצרים ישנים קדימה (FIFO)",
      "השליכו מוצרים שפג תוקפם",
    ],
    sort_order: 24,
  },
  {
    title: "ניקוי שירותים",
    description: "ניקוי וחיטוי אסלה, כיור וריצפה בשירותים",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 15,
    is_emergency: true,
    recurrence_type: "weekly",
    tips: [
      "השתמשו בחומר חיטוי ייעודי לאסלה",
      "אל תשכחו לנקות מאחורי האסלה ובסיסה",
    ],
    sort_order: 25,
  },
  {
    title: "ניקוי מקלחת",
    description: "ניקוי קירות מקלחת, ראש מקלחת ומרצפות",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "רססו חומר ניקוי והשאירו 5 דקות לפני שפשוף",
      "נגבו את המקלחת אחרי כל שימוש למניעת אבנית",
    ],
    sort_order: 26,
  },
  {
    title: "ניקוי כיור אמבטיה",
    description: "ניקוי וחיטוי כיור האמבטיה והברז",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו בסודה לשתייה לכתמי אבנית",
      "נקו גם את הניקוז למניעת סתימות",
    ],
    sort_order: 27,
  },
  {
    title: "החלפת מגבות",
    description: "החלפת מגבות רחצה וידיים במגבות נקיות",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 5,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "החליפו מגבות כל 3-4 ימים לפחות",
      "תלו מגבות כך שיתייבשו טוב למניעת עובש",
    ],
    sort_order: 28,
  },
  {
    title: "החלפת מצעים",
    description: "החלפת סדינים, ציפות כריות וציפות שמיכה",
    category: "bedroom",
    zone: "חדר שינה",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "כבסו מצעים ב-60 מעלות להרג קרדית אבק",
      "החליפו כל שבוע לשמירה על היגיינה",
    ],
    sort_order: 29,
  },
  {
    title: "ניקוי אבק בחדר שינה",
    description: "ניגוב אבק מרהיטים, מדפים ומשטחים בחדר השינה",
    category: "bedroom",
    zone: "חדר שינה",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו במטלית מיקרופייבר - אוספת אבק טוב יותר",
      "נקו מלמעלה למטה כך שהאבק נופל לרצפה",
    ],
    sort_order: 30,
  },
  {
    title: "שאיבת אבק בחדר שינה",
    description: "שאיבת אבק של רצפה ושטיחים בחדר השינה",
    category: "bedroom",
    zone: "חדר שינה",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "שאבו גם מתחת למיטה ולארונות",
      "רוקנו את מיכל השואב לפני שהוא מלא",
    ],
    sort_order: 31,
  },
  {
    title: "שאיבת אבק / הפעלת רובוט",
    description: "שאיבת אבק בסלון או הפעלת רובוט שואב",
    category: "living",
    zone: "סלון",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "סדרו חפצים מהרצפה לפני הפעלת רובוט",
      "נקו מסננים של השואב באופן קבוע",
    ],
    sort_order: 32,
  },
  {
    title: "ניגוב רצפות רטוב",
    description: "שטיפת רצפות עם מגב ומים וסבון",
    category: "living",
    zone: "סלון",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "טאטאו לפני שטיפה רטובה",
      "אל תשתמשו בהרבה מים על פרקט",
    ],
    sort_order: 33,
  },
  {
    title: "ניקוי אבק מרהיטים",
    description: "ניגוב אבק מכל הרהיטים בסלון",
    category: "living",
    zone: "סלון",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו בתרסיס ריהוט מתאים לסוג העץ",
      "אל תשכחו לנגב גם גב הטלוויזיה וציוד אלקטרוני",
    ],
    sort_order: 34,
  },
  {
    title: "כביסה (2-3 מכונות)",
    description: "הפעלת 2-3 מכונות כביסה - הפרדה לפי צבעים וסוגי בד",
    category: "laundry",
    zone: "כביסה",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "הפרידו לבנים מצבעוניים מכהים",
      "בדקו כיסים לפני הכנסה למכונה",
    ],
    sort_order: 35,
  },
  {
    title: "קיפול וסידור כביסה",
    description: "קיפול כביסה נקייה וסידורה בארונות",
    category: "laundry",
    zone: "כביסה",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "קפלו מיד אחרי הייבוש למניעת קמטים",
      "שתפו את כל המשפחה במשימה",
    ],
    sort_order: 36,
  },
  {
    title: "גיהוץ (לפי צורך)",
    description: "גיהוץ חולצות ובגדים שדורשים גיהוץ",
    category: "laundry",
    zone: "כביסה",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "גהצו כשהבגד עדיין לח קצת - קל יותר",
      "התחילו מבגדים שדורשים טמפרטורה נמוכה",
    ],
    sort_order: 37,
  },
  {
    title: "השקיית צמחים",
    description: "השקיית כל צמחי הבית ובדיקת מצבם",
    category: "general",
    zone: "כללי",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "בדקו לחות אדמה לפני השקיה - לא כל צמח צריך מים כל שבוע",
      "השקו בבוקר או בערב, לא בשמש חזקה",
    ],
    sort_order: 38,
  },
  {
    title: "ניקוי מראות",
    description: "ניקוי כל המראות בבית - אמבטיה, חדרי שינה וכניסה",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 5,
    is_emergency: false,
    recurrence_type: "weekly",
    tips: [
      "השתמשו בנוזל חלונות ועיתון ישן לתוצאה ללא פסים",
      "נגבו בתנועות עגולות",
    ],
    sort_order: 39,
  },

  // ===== BIWEEKLY (דו-שבועי) - sort_order 51-60 =====
  {
    title: "ניקוי תנור",
    description: "ניקוי עמוק של התנור מבפנים ומבחוץ",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "השתמשו בתכשיר ייעודי לתנור או סודה + חומץ",
      "חממו תנור ל-50 מעלות, כבו, ואז רססו - הניקוי קל יותר",
    ],
    sort_order: 51,
  },
  {
    title: "ניקוי פנימי של מקרר",
    description: "הוצאת כל המוצרים, ניקוי מדפים ומגירות, ובדיקת תפוגה",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "הוציאו את כל המוצרים ונגבו מדפים במים וסבון",
      "שימו קופסת סודה פתוחה לספיגת ריחות",
    ],
    sort_order: 52,
  },
  {
    title: "ניקוי עמוק אמבטיה",
    description: "ניקוי יסודי של כל חדר האמבטיה כולל פינות ומרווחים",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "השתמשו במברשת שיניים ישנה לפינות ומרווחים",
      "חומץ לבן מצוין נגד אבנית",
    ],
    sort_order: 53,
  },
  {
    title: "ניקוי אריחים באמבטיה",
    description: "ניקוי רובה בין אריחים ושפשוף אריחי קיר ורצפה",
    category: "bathroom",
    zone: "אמבטיה",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "סודה + חומץ עובדים מצוין על רובה",
      "השתמשו במברשת קשיחה לרובה ורכה לאריחים",
    ],
    sort_order: 54,
  },
  {
    title: "ניקוי חלונות (פנימי)",
    description: "ניקוי זכוכית חלונות מבפנים ומסגרות",
    category: "general",
    zone: "כללי",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "נקו ביום מעונן - שמש גורמת לייבוש מהיר ופסים",
      "נגבו בתנועות אנכיות מצד אחד ואופקיות מהצד השני",
    ],
    sort_order: 55,
  },
  {
    title: "שטיפת רצפות עמוקה",
    description: "שטיפה יסודית של כל רצפות הבית עם חומר ניקוי",
    category: "general",
    zone: "כללי",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "biweekly",
    tips: [
      "התחילו מהחדר הרחוק ביותר מהדלת",
      "שנו מים ניקוי כל חדר-שניים",
    ],
    sort_order: 56,
  },

  // ===== MONTHLY (חודשי) - sort_order 61-75 =====
  {
    title: "ניקוי מדיח (מחזור ריק עם חומץ)",
    description: "הפעלת מחזור ריק של המדיח עם חומץ לבן לניקוי ורענון",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 5,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "שימו כוס חומץ במדף העליון והפעילו מחזור חם",
      "נקו גם את המסנן בתחתית המדיח",
    ],
    sort_order: 61,
  },
  {
    title: "ניקוי ארונות מטבח",
    description: "ניקוי פנימי וחיצוני של ארונות המטבח",
    category: "kitchen",
    zone: "מטבח",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "רוקנו ארון אחד בכל פעם ונגבו מדפים",
      "בדקו תאריכי תפוגה של תבלינים ומוצרים",
    ],
    sort_order: 62,
  },
  {
    title: "ניקוי מאווררי תקרה",
    description: "ניקוי אבק מכנפי מאווררים ומנורות תקרה",
    category: "general",
    zone: "כללי",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "השתמשו בציפית כרית ישנה לניקוי כנפי מאוורר בלי לפזר אבק",
      "כבו מאוורר 10 דקות לפני ניקוי",
    ],
    sort_order: 63,
  },
  {
    title: "בדיקת מסנני מזגן",
    description: "בדיקה וניקוי מסנני המזגנים בכל החדרים",
    category: "general",
    zone: "כללי",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "שטפו מסננים במים פושרים ויבשו לפני החזרה",
      "מסנן נקי חוסך עד 15% חשמל",
    ],
    sort_order: 64,
  },
  {
    title: "ניקוי ידיות דלתות ומתגים",
    description: "חיטוי ידיות דלתות, מתגי חשמל ומשטחים נגיעה נפוצים",
    category: "general",
    zone: "כללי",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "השתמשו במגבון חיטוי או תרסיס אלכוהול",
      "אל תשכחו מתגי חשמל, שלטים ומעקות",
    ],
    sort_order: 65,
  },
  {
    title: "בדיקת תאורה והחלפת נורות",
    description: "בדיקת כל נורות הבית והחלפת נורות שרופות",
    category: "general",
    zone: "כללי",
    estimated_minutes: 10,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "עברו לנורות LED לחסכון בחשמל",
      "שמרו נורות רזרביות במלאי",
    ],
    sort_order: 66,
  },
  {
    title: "ניקוי מרפסת",
    description: "טאטוא, שטיפה וסידור המרפסת",
    category: "outdoor",
    zone: "חיצוני",
    estimated_minutes: 20,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "שטפו עם מים וסבון ומגב",
      "בדקו שניקוז המרפסת תקין",
    ],
    sort_order: 67,
  },
  {
    title: "טיפול בצמחי חוץ",
    description: "גיזום, דישון והשקיית צמחים במרפסת או בגינה",
    category: "outdoor",
    zone: "חיצוני",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "monthly",
    tips: [
      "גזמו ענפים יבשים ופרחים נובלים",
      "דשנו בהתאם לעונה ולסוג הצמח",
    ],
    sort_order: 68,
  },

  // ===== QUARTERLY (רבעוני) - sort_order 76-90 =====
  {
    title: "ניקוי חלונות (חיצוני)",
    description: "ניקוי זכוכית חלונות מבחוץ, מסגרות ותריסים",
    category: "general",
    zone: "כללי",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "השתמשו במגב מקצועי ודלי עם נוזל חלונות",
      "בקומות גבוהות - שקלו להזמין מנקה חלונות מקצועי",
    ],
    sort_order: 76,
  },
  {
    title: "ניקוי ספות וריפודים",
    description: "שאיבת אבק מספות, כריות וריפודים וטיפול בכתמים",
    category: "living",
    zone: "סלון",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "שאבו עם ראש ריפודים ייעודי",
      "בדקו הוראות ניקוי של הבד לפני טיפול בכתמים",
    ],
    sort_order: 77,
  },
  {
    title: "בדיקת מערכת מים",
    description: "בדיקת ברזים, שסתומים ונזילות בכל הבית",
    category: "general",
    zone: "כללי",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "בדקו מתחת לכיורים ולאסלות סימני רטיבות",
      "טפטוף קטן יכול לבזבז אלפי ליטרים בשנה",
    ],
    sort_order: 78,
  },
  {
    title: "ארגון ארונות בגדים",
    description: "מיון בגדים, ארגון מחדש וסילוק בגדים שלא בשימוש",
    category: "bedroom",
    zone: "חדר שינה",
    estimated_minutes: 45,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "שיטת הערימות: שמור, תרום, זרוק",
      "סובבו בגדים עונתיים - קדימה מה שרלוונטי עכשיו",
    ],
    sort_order: 79,
  },
  {
    title: "סידור מחסן",
    description: "ארגון וסידור המחסן, סילוק חפצים מיותרים",
    category: "general",
    zone: "כללי",
    estimated_minutes: 60,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "השתמשו בקופסאות שקופות עם תוויות",
      "שמרו חפצים כבדים למטה וקלים למעלה",
    ],
    sort_order: 80,
  },
  {
    title: "בדיקת אינסטלציה",
    description: "בדיקת צנרת, ניקוזים ונזילות בכל הבית",
    category: "general",
    zone: "כללי",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "שפכו מים רותחים עם סודה בניקוזים למניעת סתימות",
      "בדקו לחץ מים בכל הברזים",
    ],
    sort_order: 81,
  },
  {
    title: "בדיקת חשמל",
    description: "בדיקת שקעים, מפסקים ולוח חשמל",
    category: "general",
    zone: "כללי",
    estimated_minutes: 15,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "בדקו שמפסק פחת עובד - לחצו כפתור בדיקה",
      "אם שקע מתחמם - הזמינו חשמלאי מיד",
    ],
    sort_order: 82,
  },
  {
    title: "תחזוקת מזגנים (ניקוי + בדיקה)",
    description: "ניקוי עמוק של מזגנים, בדיקת תפקוד ומסננים",
    category: "general",
    zone: "כללי",
    estimated_minutes: 30,
    is_emergency: false,
    recurrence_type: "quarterly",
    tips: [
      "הזמינו טכנאי מזגנים פעם בשנה לפחות",
      "נקו מסננים וכנפיות עם מברשת רכה ומים",
    ],
    sort_order: 83,
  },
];

export function getCategoryColor(category: string): string {
  const colors: Record<string, string> = {
    kitchen: "#F59E0B",
    bathroom: "#3B82F6",
    living: "#8B5CF6",
    bedroom: "#EC4899",
    laundry: "#06B6D4",
    outdoor: "#84CC16",
    pets: "#F97316",
    general: "#10B981",
  };
  return colors[category] ?? "#6B7280";
}

export function getCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    kitchen: "מטבח",
    bathroom: "אמבטיה",
    living: "סלון",
    bedroom: "חדר שינה",
    laundry: "כביסה",
    outdoor: "חיצוני",
    pets: "חיות",
    general: "כללי",
  };
  return labels[category] ?? category;
}

export function getRecurrenceLabel(type: string): string {
  const labels: Record<string, string> = {
    daily: "יומי",
    weekly: "שבועי",
    biweekly: "דו-שבועי",
    monthly: "חודשי",
    quarterly: "רבעוני",
    yearly: "שנתי",
  };
  return labels[type] ?? type;
}
